<?php

/**
 * @file
 * Display Suite Bootstrap 6 6 Reponsive configuration.
 */

function ds_bootstrap_6_6_reponsive() {
  return array(
    'label' => t('Bootstrap 6 6 Reponsive'),
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_6_6_reponsive.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_6_6_reponsive.png)
    // 'image' => TRUE,
  );
}
